name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v1

      - name: Set up widdershins
        run: |
          npm install -g widdershins
          widdershins --language_tabs 'javascript:JavaScript' 'ruby:Ruby' 'python:Python' 'go:Go' --summary petstore.json -o slate/index.html.md

      - name: Set up ruby
        uses: actions/setup-ruby@v1

      - name: Set up slate
        run: |
          pwd
          FILE=petstore.json
          if [ -f "$FILE" ]; then
            echo "$FILE exists."
          else
            echo "$FILE doesn't exist."
          fi
          cd slate
          pwd
          FILE=Gemfile.lock
          if [ -f "$FILE" ]; then
            echo "$FILE exists."
          else
            echo "$FILE doesn't exist."
          fi
          FILE=config.rb
          if [ -f "$FILE" ]; then
            echo "$FILE exists."
          else
            echo "$FILE doesn't exist."
          fi
          gem install bundler
          bundle install
          cp -f index.html.md source/
          bundle exec middleman build
