name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Generate an OpenAPI format yaml from code annotation
        run: |
          sudo apt install gnupg ca-certificates
          sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 379CE192D401AB61
          echo "deb https://dl.bintray.com/go-swagger/goswagger-debian ubuntu main" | sudo tee /etc/apt/sources.list.d/goswagger.list
          sudo apt update
          sudo apt install swagger
          swagger version

      - name: Set up node
        uses: actions/setup-node@v1

      - name: Generate md from yaml
        run: |
          npm install -g widdershins
          widdershins --language_tabs 'javascript:JavaScript' 'ruby:Ruby' 'python:Python' 'go:Go' --summary petstore.json -o slate/index.html.md

      - name: Set up ruby
        uses: actions/setup-ruby@v1

      - name: Generate html from md
        run: |
          cd slate
          gem install bundler
          bundle install
          cp -f index.html.md source/
          bundle exec middleman build
