name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up go-swagger
        run: |
          download_url=$(curl -s https://api.github.com/repos/go-swagger/go-swagger/releases/latest | \
          jq -r '.assets[] | select(.name | contains("'"$(uname | tr '[:upper:]' '[:lower:]')"'_amd64")) | .browser_download_url')
          curl -o /usr/local/bin/swagger -L'#' "$download_url"
          chmod +x /usr/local/bin/swagger

      - name: Set up node
        uses: actions/setup-node@v1

      - name: Set up widdershins
        run: |
          npm install -g widdershins
          widdershins --language_tabs 'javascript:JavaScript' 'ruby:Ruby' 'python:Python' 'go:Go' --summary petstore.json -o slate/index.html.md

      - name: Set up ruby
        uses: actions/setup-ruby@v1

      - name: Set up slate
        run: |
          cd slate
          gem install bundler
          bundle install
          cp -f index.html.md source/
          bundle exec middleman build
